### ISSUE TITLE
Elm 0.19 support

### ISSUE THREAD

**Issue by rl-king** [mindphaze/flycheck-elm#16]
Elm 0.19 added additional information and changed the structure of the output JSON containing the errors. 

I'm not sure if there is spec somewhere on what the full error could look like. There is however this package that decodes it in to Elm values https://package.elm-lang.org/packages/elm/project-metadata-utils/latest/Elm-Error

**Comment by purcell** [comment]
Addressed by #17 - please test if you have time.

**Comment by purcell** [comment]
Closing this for now since #17 is merged, but it's quite possible further work will be needed, in which case you should feel free to submit a specific bug report.
